services:
  app:
    build: .
    ports:
      - 5000:5000      
    volumes:
      - .:/home/node/app
      - logvolume01:/var/log
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USERNAME: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql